### ISSUE TITLE
Move `tslib` to dependencies from devDependencies

### ISSUE THREAD

**Issue by dmattia** [m-radzikowski/aws-sdk-client-mock#29]
This module does rely on `tslib` at runtime, so strict node systems like yarn v2 and esbuild will not allow it to run without a patch.

A temporary workaround for yarn v2 projects is to put:

```yaml
packageExtensions:
  aws-sdk-client-mock@*:
    dependencies:
      tslib: '*
```

In your .yarnrc.yml file in order to patch this library, but the better fix will be to update this package to correctly put `tslib` as a dependency.

See similar issues: https://github.com/styled-components/styled-components/issues/3082
